// Rutas de Page
export const HOME = "/"
export const HOME_SISTEMA_GESTION = "/HomeSistemaGestion"

export const LOGIN = "/area-empleados/Login"
export const HOME_ADMIN = "/Admin"
export const FLUJO_CAJA = "/FlujoCaja"
export const LIBRO_DIARIO = "/LibroDiario"
export const TERRENOS = "/Terrenos"
export const EMPLEADOS = "/Empleados"
export const VTA_TERRENOS = "/VentaTerrenos"
export const COMPRA_MATERIALES = "/CompraMateriales"
export const STOCK = "/Stock"
export const CLIENTES = "/Clientes"
export const DEPARTAMENTOS = "/Departamentos"
export const PAGOS_DPTO = "/PagosDepartamentos"
export const OBRAS = "/Obras"
export const OPERACIONES = "/Operaciones"
export const USUARIO = "/Usuarios"
export const UNAUTHORIZED = "/unauthorized"
export const PAGOS = "/Pagos"
export const VEHICULOS = "/Vehiculos"
export const PENDIENTES = "/Pendientes"
export const VIAJES = "/Viajes"
export const DETALLEVIAJES = "/DetalleViajes" 
export const ALQUILER = "/Alquiler"
export const REMUNERACIONES = "/Remuneraciones"
// export const NOT_FOUND = "/notfound"

