// Rutas de Page
export const HOME = "/"
export const HOME_SISTEMA_GESTION = "/HomeSistemaGestion"

export const LOGIN = "/area-empleados/Login"
export const RECUPERAR = "/area-empleados/RecuperarContraseña"
export const CERTIFICADOS = "/Admin/Certificados"
export const HOME_ADMIN = "/Admin"
export const FLUJO_CAJA = "/Admin/FlujoCaja"
export const LIBRO_DIARIO = "/Admin/LibroDiario"
export const TERRENOS = "/Admin/Terrenos"
export const EMPLEADOS = "/Admin/Empleados"
export const VTA_TERRENOS = "/Admin/VentaTerrenos"
export const COMPRA_MATERIALES = "/Admin/CompraMateriales"
export const STOCK = "/AdminStock"
export const CLIENTES = "/Admin/Clientes"
export const DEPARTAMENTOS = "/Admin/admin/Departamentos"
export const PAGOS_DPTO = "/Admin/PagosDepartamentos"
export const OBRAS = "/Admin/Obras"
export const OPERACIONES = "/Admin/Operaciones"
export const USUARIO = "/Admin/Usuarios"
export const UNAUTHORIZED = "/Admin/unauthorized"
export const PAGOS = "/Admin/Pagos"
export const VEHICULOS = "/Admin/Vehiculos"
export const PENDIENTES = "/Admin/Pendientes"
export const VIAJES = "/Admin/Viajes"
export const DETALLEVIAJES = "/Admin/DetalleViajes" 
export const ALQUILER = "/Admin/Alquiler"
export const REMUNERACIONES = "/Admin/Remuneraciones"
// export const NOT_FOUND = "/notfound"

